name: Sync Anime Submodule

on:
  workflow_dispatch:
  repository_dispatch:
    types: [submodule_updated] # Listen for this specific "ping"
  schedule:
    - cron: '0 */6 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Submodule
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git submodule update --remote --init --force project/anime-collection
          
          if git diff --quiet; then
            echo "No changes found. Submodule already up to date."
          else
            git add project/anime-collection
            git commit -m "Auto-sync: update anime-collection to latest"
            git push origin main
          fi
